name: Deploy Frontend to Apache Server

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    # Step 3: Install dependencies and build
    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build

    # Step 4: Deploy to Apache server and restart Gunicorn using scp with SSH key
    - name: Deploy to Apache server and restart Gunicorn
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        # Configure SSH key
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        
        # Add host to known_hosts to avoid interactive prompt
        ssh-keyscan -H ninjastorm.firelab.org >> ~/.ssh/known_hosts
        
        # Use scp to transfer files for the front-end
        scp -i ~/.ssh/id_rsa -r ./out/* gunjan@ninjastorm.firelab.org:/var/www/html/hpc_dashboard
        
        # Transfer app.py to the server
        scp -i ~/.ssh/id_rsa server/app.py gunjan@ninjastorm.firelab.org:/home/gunjan/app.py
        
        # Restart Gunicorn service
        ssh -i ~/.ssh/id_rsa gunjan@ninjastorm.firelab.org << 'EOF'
        echo "Restarting hpc_dashboard Gunicorn service..."
        if sudo systemctl restart hpc_dashboard; then
            echo "Gunicorn service restarted successfully."
        else
            echo "Failed to restart Gunicorn service." >&2
            exit 1
        fi
